package org.example.project.qdcore.util.node

import org.example.project.qdcore.ast.AstRoot
import org.example.project.qdcore.ast.InlineContent
import org.example.project.qdcore.ast.NestableNode
import org.example.project.qdcore.ast.Node
import org.example.project.qdcore.ast.base.inline.CriticalContent
import org.example.project.qdcore.ast.base.inline.PlainTextNode
import org.example.project.qdcore.ast.dsl.buildInline
import org.example.project.qdcore.ast.quarkdown.inline.TextSymbol
import org.example.project.qdcore.visitor.node.NodeVisitor

/**
 * Groups nodes into an [AstRoot] container.
 * @return an empty [AstRoot] if `null`
 */
fun List<Node>?.group(): AstRoot = AstRoot(this.orEmpty())

/**
 * Returns a sequence of all nodes in the tree, where [this] is the root node.
 * The sequence is generated by traversing the tree in depth-first order.
 * The root node is excluded from the sequence.
 *
 * Example:
 *
 * Input (nested node tree):
 * ```
 * AstRoot
 *   BlockQuote
 *     Paragraph
 *       Text
 *   Paragraph
 *     Strong
 *       Text
 *     Text
 *     Emphasis
 *       Text
 * ```
 *
 * Output (flattened sequence):
 * ```
 * BlockQuote
 * Paragraph
 * Text
 * Paragraph
 * Strong
 * Text
 * Text
 * Emphasis
 * Text
 * ```
 *
 * @return flattened sequence of children nodes, excluding [this] root node
 */
fun NestableNode.flattenedChildren(): Sequence<Node> =
    sequence {
        // DFS traversal.
        for (child in children) {
            yield(child)
            if (child is NestableNode) {
                yieldAll(child.flattenedChildren())
            }
        }
    }

/**
 * Converts processed [InlineContent] to its plain text representation.
 * For example, the Markdown input `foo **bar `baz`**` has `foo bar baz` as its plain text.
 *
 * Note: this is a quick and efficient implementation, practical for the use cases inside the core compiler
 * (e.g., stripping away formatting from image labels).
 * For a full-fledged plain text rendering, see the `quarkdown-plaintext` module instead.
 *
 * @param renderer optional renderer to use to render critical content and text symbols
 * @return plain text of the inline content
 * @see PlainTextNode
 */
fun InlineContent.toPlainText(renderer: NodeVisitor<CharSequence>? = null): String {
    val builder = StringBuilder()

    // Visits the tree and appends the text content of each node.
    AstRoot(this).flattenedChildren().forEach {
        when (it) {
            is CriticalContent if renderer != null -> builder.append(renderer.visit(it))
            is TextSymbol if renderer != null -> builder.append(renderer.visit(it))
            is PlainTextNode -> builder.append(it.text)
        }
    }

    return builder.toString()
}

/**
 * Strips rich content from [this] inline content and returns a new inline content with only one [org.example.project.qdcore.ast.base.inline.Text] child,
 * which contains the plain text representation of [this] inline content.
 * @param renderer optional renderer to use to render critical content and text symbols
 * @return inline content with only plain text
 * @see toPlainText
 */
fun InlineContent.stripRichContent(renderer: NodeVisitor<CharSequence>? = null): InlineContent = buildInline { text(toPlainText(renderer)) }
